# Lab 4: Getting Started with Pandas

**Course:** Data Science and Big Data Analytics  
**Submission:** Jupyter Notebook / Python code with output  

This notebook completes all required Lab 4 tasks using Pandas.  
Each task includes Python code, comments, and displayed output.

## Setup

Run this first to import Pandas and configure display options.

In [6]:
# Import pandas library
import pandas as pd
import numpy as np
from pathlib import Path

# Display more columns and wider output for easier review
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

# Define the input Excel file path
excel_file = Path("Lab 4 - Automobile.xls")

# Define the cleaned CSV output file path
cleaned_csv_file = Path("Lab_4_Automobile_Cleaned.csv")

print("Pandas version:", pd.__version__)
print("Current working directory:", Path.cwd())
print("Expected Excel file:", excel_file)

Pandas version: 2.3.3
Current working directory: c:\Users\dubey\Documents\UC_GitLab\Summer_2026_BI_Sem_1\Data_Science_and_Big_Data_Analytics\Lab_4_Pandas
Expected Excel file: Lab 4 - Automobile.xls

# Part 1: Working with Series

## Task 1: Create and display a one-dimensional Series

In [7]:
# Create a Pandas Series using sample string data
student_names = pd.Series(["Alok", "Ravi", "Neha", "Priya", "Amit"])

# Display the Series
print("Task 1: One-dimensional Pandas Series")
print(student_names)

Task 1: One-dimensional Pandas Series
0     Alok
1     Ravi
2     Neha
3    Priya
4     Amit
dtype: object

## Task 2: Perform arithmetic operations on two Series

In [8]:
# Create two Pandas Series
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

# Perform arithmetic operations
addition = series1 + series2
subtraction = series1 - series2
multiplication = series1 * series2
division = series1 / series2

# Display results
print("Series 1:")
print(series1)

print("\nSeries 2:")
print(series2)

print("\nAddition:")
print(addition)

print("\nSubtraction:")
print(subtraction)

print("\nMultiplication:")
print(multiplication)

print("\nDivision:")
print(division)

Series 1:
0     2
1     4
2     6
3     8
4    10
dtype: int64

Series 2:
0    1
1    3
2    5
3    7
4    9
dtype: int64

Addition:
0     3
1     7
2    11
3    15
4    19
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    1
dtype: int64

Multiplication:
0     2
1    12
2    30
3    56
4    90
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

# Part 2: Working with the Automobile Dataset

## Task 3: Load the dataset using Pandas

In [9]:
# Load the Excel file into a Pandas DataFrame
# xlrd is required for reading .xls files.
auto_df = pd.read_excel(excel_file)

# Display basic dataset information
print("Task 3: Automobile dataset loaded successfully.")
print("Shape of dataset:", auto_df.shape)
print("\nColumn names:")
print(auto_df.columns.tolist())

Task 3: Automobile dataset loaded successfully.
Shape of dataset: (61, 10)

Column names:
['index', 'company', 'body-style', 'wheel-base', 'length', 'engine-type', 'num-of-cylinders', 'horsepower', 'average-mileage', 'price']

## Task 4: Print the first five and last five rows

In [10]:
# Display first five rows
print("First five rows:")
display(auto_df.head())

# Display last five rows
print("Last five rows:")
display(auto_df.tail())

First five rows:

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

Last five rows:

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

## Task 5: Remove records containing '?', 'n.a', or NaN values and save cleaned DataFrame

In [11]:
# Replace invalid values '?' and 'n.a' with NaN
auto_cleaned_df = auto_df.replace(["?", "n.a"], np.nan)

# Remove rows containing any NaN values
auto_cleaned_df = auto_cleaned_df.dropna()

# Save cleaned DataFrame to CSV
auto_cleaned_df.to_csv(cleaned_csv_file, index=False)

# Display result
print("Original dataset shape:", auto_df.shape)
print("Cleaned dataset shape:", auto_cleaned_df.shape)
print("Cleaned CSV saved as:", cleaned_csv_file)

display(auto_cleaned_df.head())

Original dataset shape: (61, 10)
Cleaned dataset shape: (58, 10)
Cleaned CSV saved as: Lab_4_Automobile_Cleaned.csv

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

## Helper Cell: Identify important columns

Different Automobile datasets may use slightly different column names.  
This cell detects likely company, price, and mileage columns.

In [12]:
# Helper function to find a column by possible names
def find_column(df, possible_names):
    normalized_columns = {col.lower().strip().replace(" ", "_").replace("-", "_"): col for col in df.columns}
    for name in possible_names:
        key = name.lower().strip().replace(" ", "_").replace("-", "_")
        if key in normalized_columns:
            return normalized_columns[key]
    return None

# Detect commonly used columns
company_col = find_column(auto_cleaned_df, ["company", "make", "manufacturer", "car_company"])
price_col = find_column(auto_cleaned_df, ["price"])
mileage_col = find_column(auto_cleaned_df, ["average_mileage", "average-mileage", "mileage", "city_mpg", "highway_mpg"])

print("Detected company column:", company_col)
print("Detected price column:", price_col)
print("Detected mileage column:", mileage_col)

# Convert price and mileage columns to numeric if they exist
if price_col:
    auto_cleaned_df[price_col] = pd.to_numeric(auto_cleaned_df[price_col], errors="coerce")

if mileage_col:
    auto_cleaned_df[mileage_col] = pd.to_numeric(auto_cleaned_df[mileage_col], errors="coerce")

Detected company column: company
Detected price column: price
Detected mileage column: average-mileage

## Task 6: Find and print the most expensive car

In [13]:
# Find the most expensive car based on the price column
most_expensive_car = auto_cleaned_df.loc[auto_cleaned_df[price_col].idxmax()]

print("Most expensive car in the dataset")
print("Company:", most_expensive_car[company_col])
print("Price:", most_expensive_car[price_col])
print("\nFull details:")
display(most_expensive_car.to_frame().T)

Most expensive car in the dataset
Company: mercedes-benz
Price: 45400.0

Full details:

   index        company body-style wheel-base length engine-type num-of-cylinders horsepower average-mileage    price
35    47  mercedes-benz    hardtop      112.0  199.2        ohcv            eight        184              14  45400.0

## Task 7: Print all details of cars manufactured by Toyota

In [14]:
# Filter cars manufactured by Toyota
toyota_cars = auto_cleaned_df[auto_cleaned_df[company_col].astype(str).str.lower() == "toyota"]

print("Toyota cars:")
display(toyota_cars)

Toyota cars:

    index company body-style  wheel-base  length engine-type num-of-cylinders  horsepower  average-mileage    price
48     66  toyota  hatchback        95.7   158.7         ohc             four          62               35   5348.0
49     67  toyota  hatchback        95.7   158.7         ohc             four          62               31   6338.0
50     68  toyota  hatchback        95.7   158.7         ohc             four          62               31   6488.0
51     69  toyota      wagon        95.7   169.7         ohc             four          62               31   6918.0
52     70  toyota      wagon        95.7   169.7         ohc             four          62               27   7898.0
53     71  toyota      wagon        95.7   169.7         ohc             four          62               27   8778.0
54     79  toyota      wagon       104.5   187.8        dohc              six         156               19  15750.0

## Task 8: Count and display total number of cars per company

In [15]:
# Count number of cars per company
cars_per_company = auto_cleaned_df[company_col].value_counts()

print("Total number of cars per company:")
print(cars_per_company)

Total number of cars per company:
company
toyota           7
bmw              6
mazda            5
nissan           5
mercedes-benz    4
audi             4
volkswagen       4
mitsubishi       4
chevrolet        3
alfa-romero      3
jaguar           3
honda            3
porsche          2
dodge            2
volvo            2
isuzu            1
Name: count, dtype: int64

## Task 9: Display the most expensive car from each company

In [16]:
# Sort by company and price, then keep the highest priced car for each company
most_expensive_by_company = (
    auto_cleaned_df.sort_values(by=[company_col, price_col], ascending=[True, False])
    .groupby(company_col)
    .head(1)
    .reset_index(drop=True)
)

print("Most expensive car from each company:")
display(most_expensive_by_company)

Most expensive car from each company:

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
0,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
1,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0
2,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
3,18,chevrolet,sedan,94.5,158.8,ohc,four,70,38,6575.0
4,19,dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
5,28,honda,sedan,96.5,175.4,ohc,four,101,24,12945.0
6,30,isuzu,sedan,94.3,170.7,ohc,four,78,24,6785.0
7,35,jaguar,sedan,102.0,191.7,ohcv,twelve,262,13,36000.0
8,43,mazda,sedan,104.9,175.0,ohc,four,72,31,18344.0
9,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0
10,52,mitsubishi,sedan,96.3,172.4,ohc,four,88,25,8189.0
11,57,nissan,sedan,100.4,184.6,ohcv,six,152,19,13499.0
12,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
13,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0
14,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
15,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

## Task 10: Calculate average mileage for each car company

In [17]:
# Calculate average mileage by company
average_mileage_by_company = (
    auto_cleaned_df.groupby(company_col)[mileage_col]
    .mean()
    .sort_values(ascending=False)
)

print("Average mileage by company:")
print(average_mileage_by_company)

Average mileage by company:
company
chevrolet        41.000000
volkswagen       31.750000
nissan           31.400000
dodge            31.000000
mitsubishi       29.500000
toyota           28.714286
mazda            28.000000
honda            26.333333
isuzu            24.000000
volvo            23.000000
alfa-romero      20.333333
audi             20.000000
bmw              19.000000
mercedes-benz    18.000000
porsche          17.000000
jaguar           14.333333
Name: average-mileage, dtype: float64

## Task 11: Sort all cars in ascending order based on price

In [18]:
# Sort all cars by price in ascending order
cars_sorted_by_price = auto_cleaned_df.sort_values(by=price_col, ascending=True)

print("Cars sorted by price in ascending order:")
display(cars_sorted_by_price)

Cars sorted by price in ascending order:

,index,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
13,16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151.0
27,36,mazda,hatchback,93.1,159.1,ohc,four,68,30,5195.0
48,66,toyota,hatchback,95.7,158.7,ohc,four,62,35,5348.0
36,49,mitsubishi,hatchback,93.7,157.3,ohc,four,68,37,5389.0
28,37,mazda,hatchback,93.1,159.1,ohc,four,68,31,6095.0
37,50,mitsubishi,hatchback,93.7,157.3,ohc,four,68,31,6189.0
17,20,dodge,hatchback,93.7,157.3,ohc,four,68,31,6229.0
14,17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295.0
49,67,toyota,hatchback,95.7,158.7,ohc,four,62,31,6338.0
16,19,dodge,hatchback,93.7,157.3,ohc,four,68,31,6377.0
50,68,toyota,hatchback,95.7,158.7,ohc,four,62,31,6488.0
15,18,chevrolet,sedan,94.5,158.8,ohc,four,70,38,6575.0
41,54,nissan,sedan,94.5,165.3,ohc,four,69,31,6649.0
21,30,isuzu,sedan,94.3,170.7,ohc,four,78,24,6785.0
29,38,mazda,hatchback,93.1,159.1,ohc,four,68,31,6795.0
42,55,nissan,sedan,94.5,165.3,ohc,four,69,31,6849.0
51,69,toyota,wagon,95.7,169.7,ohc,four,62,31,6918.0
38,51,mitsubishi,sedan,96.3,172.4,ohc,four,88,25,6989.0
40,53,nissan,sedan,94.5,165.3,ohc,four,55,45,7099.0
18,27,honda,wagon,96.5,157.1,ohc,four,76,30,7295.0
43,56,nissan,wagon,94.5,170.2,ohc,four,69,31,7349.0
55,80,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7775.0
52,70,toyota,wagon,95.7,169.7,ohc,four,62,27,7898.0
56,81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
57,82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
39,52,mitsubishi,sedan,96.3,172.4,ohc,four,88,25,8189.0
53,71,toyota,wagon,95.7,169.7,ohc,four,62,27,8778.0
58,86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
20,29,honda,sedan,96.5,169.1,ohc,four,100,25,10345.0
30,39,mazda,hatchback,95.3,169.0,rotor,two,101,17,11845.0
59,87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
19,28,honda,sedan,96.5,175.4,ohc,four,101,24,12945.0
60,88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0
0,0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
44,57,nissan,sedan,100.4,184.6,ohcv,six,152,19,13499.0
3,3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
5,5,audi,sedan,99.8,177.3,ohc,five,110,19,15250.0
54,79,toyota,wagon,104.5,187.8,dohc,six,156,19,15750.0
7,9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430.0
2,2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
1,1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
8,10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925.0
4,4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
31,43,mazda,sedan,104.9,175.0,ohc,four,72,31,18344.0
6,6,audi,wagon,105.8,192.7,ohc,five,110,19,18920.0
9,11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970.0
32,44,mercedes-benz,sedan,110.0,190.9,ohc,five,123,22,25552.0
33,45,mercedes-benz,wagon,110.0,190.9,ohc,five,123,22,28248.0
10,13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760.0
24,33,jaguar,sedan,113.0,199.6,dohc,six,176,15,32250.0
45,61,porsche,hardtop,89.5,168.9,ohcf,six,207,17,34028.0
25,34,jaguar,sedan,113.0,199.6,dohc,six,176,15,35550.0
26,35,jaguar,sedan,102.0,191.7,ohcv,twelve,262,13,36000.0
12,15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880.0
46,62,porsche,convertible,89.5,168.9,ohcf,six,207,17,37028.0
34,46,mercedes-benz,sedan,120.9,208.1,ohcv,eight,184,14,40960.0
11,14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315.0
35,47,mercedes-benz,hardtop,112.0,199.2,ohcv,eight,184,14,45400.0

# Part 3: Combining DataFrames

## Task 12: Create two DataFrames and concatenate them

In [19]:
# Create dictionaries for German and Japanese cars
GermanCars = {
    "Company": ["Ford", "Mercedes", "BMV", "Audi"],
    "Price": [23845, 171995, 135925, 71400]
}

japaneseCars = {
    "Company": ["Toyota", "Honda", "Nissan", "Mitsubishi "],
    "Price": [29995, 23600, 61500, 58900]
}

# Convert dictionaries to DataFrames
german_cars_df = pd.DataFrame(GermanCars)
japanese_cars_df = pd.DataFrame(japaneseCars)

# Concatenate both DataFrames
combined_cars_df = pd.concat([german_cars_df, japanese_cars_df], ignore_index=True)

print("German Cars DataFrame:")
display(german_cars_df)

print("Japanese Cars DataFrame:")
display(japanese_cars_df)

print("Concatenated Cars DataFrame:")
display(combined_cars_df)

German Cars DataFrame:

    Company   Price
0      Ford   23845
1  Mercedes  171995
2       BMV  135925
3      Audi   71400

Japanese Cars DataFrame:

       Company  Price
0       Toyota  29995
1        Honda  23600
2       Nissan  61500
3  Mitsubishi   58900

Concatenated Cars DataFrame:

       Company   Price
0         Ford   23845
1     Mercedes  171995
2          BMV  135925
3         Audi   71400
4       Toyota   29995
5        Honda   23600
6       Nissan   61500
7  Mitsubishi    58900

## Task 13: Merge Car_Price and Car_Horsepower DataFrames

In [20]:
# Create dictionaries for car price and horsepower
Car_Price = {
    "Company": ["Toyota", "Honda", "BMV", "Audi"],
    "Price": [23845, 17995, 135925, 71400]
}

car_Horsepower = {
    "Company": ["Toyota", "Honda", "BMV", "Audi"],
    "horsepower": [141, 80, 182, 160]
}

# Convert dictionaries to DataFrames
car_price_df = pd.DataFrame(Car_Price)
car_horsepower_df = pd.DataFrame(car_Horsepower)

# Merge DataFrames on Company column
merged_car_df = pd.merge(car_price_df, car_horsepower_df, on="Company")

print("Car Price DataFrame:")
display(car_price_df)

print("Car Horsepower DataFrame:")
display(car_horsepower_df)

print("Merged DataFrame:")
display(merged_car_df)

Car Price DataFrame:

  Company   Price
0  Toyota   23845
1   Honda   17995
2     BMV  135925
3    Audi   71400

Car Horsepower DataFrame:

  Company  horsepower
0  Toyota         141
1   Honda          80
2     BMV         182
3    Audi         160

Merged DataFrame:

  Company   Price  horsepower
0  Toyota   23845         141
1   Honda   17995          80
2     BMV  135925         182
3    Audi   71400         160

# End of Lab 4

This notebook completed all required tasks:
- Pandas Series creation and arithmetic operations
- Automobile dataset loading, cleaning, filtering, grouping, sorting, and analysis
- DataFrame concatenation and merging