In [2]:
import pandas as pd

In [6]:
df_prices = pd.read_csv("ETF prices.csv")

df_prices.head()

  fund_symbol  price_date   open   high    low  close  adj_close  volume
0         AAA  2020-09-09  25.10  25.12  25.07  25.07      24.85   17300
1         AAA  2020-09-10  25.06  25.07  25.05  25.07      24.85   23500
2         AAA  2020-09-11  25.04  25.05  25.02  25.03      24.81   33400
3         AAA  2020-09-14  25.01  25.06  25.01  25.02      24.80   13100
4         AAA  2020-09-15  25.02  25.03  25.01  25.01      24.79   12100

In [9]:
df_prices.shape
df_prices.columns
df_prices["fund_symbol"].unique()[:20]

array(['AAA', 'AAAU', 'AADR', 'AAXJ', 'ABEQ', 'ACES', 'ACIO', 'ACSI',
       'ACTV', 'ACVF', 'ACWF', 'ACWI', 'ACWV', 'ACWX', 'ADFI', 'ADIV',
       'ADME', 'ADRE', 'AEMB', 'AESR'], dtype=object)

In [10]:
df_etf = df_prices[df_prices["fund_symbol"] == "AAXJ"]

df_etf.head()

     fund_symbol  price_date   open   high    low  close  adj_close  volume
4002        AAXJ  2008-08-15  50.13  50.13  50.13  50.13      40.23     100
4003        AAXJ  2008-08-18  49.77  49.77  49.00  49.00      39.32   25600
4004        AAXJ  2008-08-19  48.34  48.34  48.34  48.34      38.79     100
4005        AAXJ  2008-08-20  49.05  49.05  49.02  49.02      39.34    4000
4006        AAXJ  2008-08-21  49.02  49.02  49.02  49.02      39.34       0

In [11]:
df_etf.shape

(3347, 8)

In [13]:
df_etf.loc[:, "price_date"] = pd.to_datetime(df_etf["price_date"])

In [14]:
df_etf = df_etf.sort_values("price_date")

df_etf.head()

     fund_symbol price_date   open   high    low  close  adj_close  volume
4002        AAXJ 2008-08-15  50.13  50.13  50.13  50.13      40.23     100
4003        AAXJ 2008-08-18  49.77  49.77  49.00  49.00      39.32   25600
4004        AAXJ 2008-08-19  48.34  48.34  48.34  48.34      38.79     100
4005        AAXJ 2008-08-20  49.05  49.05  49.02  49.02      39.34    4000
4006        AAXJ 2008-08-21  49.02  49.02  49.02  49.02      39.34       0

In [15]:
df_etf["return"] = df_etf["adj_close"].pct_change()

df_etf.head()

,fund_symbol,price_date,open,high,low,close,adj_close,volume,return
4002,AAXJ,2008-08-15,50.13,50.13,50.13,50.13,40.23,100,NaN
4003,AAXJ,2008-08-18,49.77,49.77,49.00,49.00,39.32,25600,-0.022620
4004,AAXJ,2008-08-19,48.34,48.34,48.34,48.34,38.79,100,-0.013479
4005,AAXJ,2008-08-20,49.05,49.05,49.02,49.02,39.34,4000,0.014179
4006,AAXJ,2008-08-21,49.02,49.02,49.02,49.02,39.34,0,0.000000

In [16]:
df_etf = df_etf.dropna()

In [17]:
df_etf["return"] = df_etf["adj_close"].pct_change()

df_etf.head()

,fund_symbol,price_date,open,high,low,close,adj_close,volume,return
4003,AAXJ,2008-08-18,49.77,49.77,49.00,49.00,39.32,25600,NaN
4004,AAXJ,2008-08-19,48.34,48.34,48.34,48.34,38.79,100,-0.013479
4005,AAXJ,2008-08-20,49.05,49.05,49.02,49.02,39.34,4000,0.014179
4006,AAXJ,2008-08-21,49.02,49.02,49.02,49.02,39.34,0,0.000000
4007,AAXJ,2008-08-22,49.25,49.25,49.16,49.22,39.50,3600,0.004067