In [1]:
# Lab 7: Data Wrangling
# Step 1: Import required libraries and read the dataset

import pandas as pd
import numpy as np

# Read the Excel dataset
# Make sure this file is in the same folder as your notebook
cancer_df = pd.read_excel("Lab 7 - Cancer.xls")

# Display the first 5 rows
cancer_df.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong

In [2]:
# Step 2: Display the data types of each column

cancer_df.dtypes

patient_id                 int64
clump_thickness          float64
cell_size_uniformity     float64
cell_shape_uniformity      int64
marginal_adhesion          int64
single_ep_cell_size        int64
bare_nuclei               object
bland_chromatin          float64
normal_nucleoli          float64
mitoses                    int64
class                     object
doctor_name               object
dtype: object

In [3]:
# Step 3: Generate summary statistics for numeric columns

cancer_df.describe()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bland_chromatin,normal_nucleoli,mitoses
count,6.990000e+02,698.000000,698.000000,699.000000,699.000000,699.000000,695.000000,698.000000,699.000000
mean,1.071704e+06,4.416905,3.137536,3.207439,2.793991,3.216023,3.447482,2.868195,1.589413
std,6.170957e+05,2.817673,3.052575,2.971913,2.843163,2.214300,2.441191,3.055647,1.715078
min,6.163400e+04,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,8.706885e+05,2.000000,1.000000,1.000000,1.000000,2.000000,2.000000,1.000000,1.000000
50%,1.171710e+06,4.000000,1.000000,1.000000,1.000000,2.000000,3.000000,1.000000,1.000000
75%,1.238298e+06,6.000000,5.000000,5.000000,3.500000,4.000000,5.000000,4.000000,1.000000
max,1.345435e+07,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [4]:
# Step 4: Group the dataset by class and doctor_name

grouped_df = cancer_df.groupby(['class', 'doctor_name']).size().reset_index(name='record_count')

# Display grouped result
grouped_df

       class doctor_name  record_count
0     benign     Dr. Doe           127
1     benign     Dr. Lee           121
2     benign   Dr. Smith           102
3     benign    Dr. Wong           108
4  malignant     Dr. Doe            58
5  malignant     Dr. Lee            60
6  malignant   Dr. Smith            74
7  malignant    Dr. Wong            49

In [5]:
# Step 5: Provide a summary of missing values within the dataset

missing_values_summary = cancer_df.isnull().sum()

# Display missing values column-wise
missing_values_summary

patient_id               0
clump_thickness          1
cell_size_uniformity     1
cell_shape_uniformity    0
marginal_adhesion        0
single_ep_cell_size      0
bare_nuclei              2
bland_chromatin          4
normal_nucleoli          1
mitoses                  0
class                    0
doctor_name              0
dtype: int64

In [6]:
# Step 6: Drop all rows that contain missing data

cancer_df_clean = cancer_df.dropna()

# Display the original and cleaned dataset shapes
print("Original dataset shape:", cancer_df.shape)
print("Dataset shape after dropping missing values:", cancer_df_clean.shape)

# Display first 5 rows of cleaned dataset
cancer_df_clean.head()

Original dataset shape: (699, 12)
Dataset shape after dropping missing values: (690, 12)

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong

In [7]:
# Step 7: Summarize the number of unique values in each column

unique_values_summary = cancer_df_clean.nunique()

# Display number of unique values column-wise
unique_values_summary

patient_id               637
clump_thickness           10
cell_size_uniformity      10
cell_shape_uniformity     10
marginal_adhesion         10
single_ep_cell_size       10
bare_nuclei               11
bland_chromatin           10
normal_nucleoli           10
mitoses                    9
class                      2
doctor_name                4
dtype: int64

In [8]:
# Step 8: Display unique value details for each column

for column in cancer_df_clean.columns:
    print(f"\nColumn: {column}")
    print(f"Number of unique values: {cancer_df_clean[column].nunique()}")
    print("Sample unique values:")
    print(cancer_df_clean[column].unique()[:10])

Column: patient_id
Number of unique values: 637
Sample unique values:
[1000025 1002945 1015425 1016277 1017023 1017122 1018561 1033078 1035283
 1036172]

Column: clump_thickness
Number of unique values: 10
Sample unique values:
[ 5.  3.  6.  4.  8.  2.  1.  7. 10.  9.]

Column: cell_size_uniformity
Number of unique values: 10
Sample unique values:
[ 1.  4.  8. 10.  2.  7.  3.  5.  6.  9.]

Column: cell_shape_uniformity
Number of unique values: 10
Sample unique values:
[ 1  4  8 10  2  5  6  7  3  9]

Column: marginal_adhesion
Number of unique values: 10
Sample unique values:
[ 1  5  3  8  4  6 10  2  9  7]

Column: single_ep_cell_size
Number of unique values: 10
Sample unique values:
[ 2  7  3  1  6  4  5  8 10  9]

Column: bare_nuclei
Number of unique values: 11
Sample unique values:
[1 10 2 4 3 9 7 '?' 5 8]

Column: bland_chromatin
Number of unique values: 10
Sample unique values:
[ 3.  9.  1.  2.  5.  4.  7.  8.  6. 10.]

Column: normal_nucleoli
Number of unique values: 10
Sample unique values:
[ 1.  2.  7.  5.  3.  4. 10.  6.  9.  8.]

Column: mitoses
Number of unique values: 9
Sample unique values:
[ 1  5  4  2  3  7 10  8  6]

Column: class
Number of unique values: 2
Sample unique values:
['benign' 'malignant']

Column: doctor_name
Number of unique values: 4
Sample unique values:
['Dr. Doe' 'Dr. Smith' 'Dr. Lee' 'Dr. Wong']

In [9]:
# Step 9: Find duplicate values in patient_id

patient_id_counts = cancer_df_clean['patient_id'].value_counts()

# Display patient_id values that appear more than once
duplicate_patient_ids = patient_id_counts[patient_id_counts > 1]

duplicate_patient_ids

patient_id
1182404    6
1276091    5
1198641    3
897471     2
411453     2
734111     2
1158247    2
1293439    2
1143978    2
560680     2
1277792    2
320675     2
1116192    2
1116116    2
1115293    2
704097     2
1105524    2
1100524    2
385103     2
1171710    2
1168736    2
1339781    2
1173347    2
1174057    2
1299596    2
695091     2
1238777    2
1321942    2
1240603    2
1218860    2
1061990    2
1212422    2
1299924    2
769612     2
733639     2
1320077    2
654546     2
1017023    2
1070935    2
493452     2
798429     2
466906     2
1114570    2
1354840    2
1033078    2
Name: count, dtype: int64

In [10]:
# Step 10: Find the patient_id that appears most frequently

most_frequent_patient_id = patient_id_counts.idxmax()
most_frequent_count = patient_id_counts.max()

print("Most frequently appearing patient_id:", most_frequent_patient_id)
print("Number of times it appears:", most_frequent_count)

Most frequently appearing patient_id: 1182404
Number of times it appears: 6

In [11]:
# Step 11: Remove patients where patient_id appears more than two times

# Identify patient IDs that appear more than two times
patients_more_than_two = patient_id_counts[patient_id_counts > 2].index

# Filter the cleaned dataset to remove those patient IDs
cancer_df_filtered = cancer_df_clean[~cancer_df_clean['patient_id'].isin(patients_more_than_two)]

# Display shape before and after filtering
print("Shape before removing patients appearing more than two times:", cancer_df_clean.shape)
print("Shape after removing patients appearing more than two times:", cancer_df_filtered.shape)

# Display first 5 rows of filtered dataset
cancer_df_filtered.head()

Shape before removing patients appearing more than two times: (690, 12)
Shape after removing patients appearing more than two times: (676, 12)

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong

In [12]:
# Step 12: Create a new DataFrame containing patient_id and doctor_name

categorical_df = cancer_df_filtered[['patient_id', 'doctor_name']].copy()

# Add doctor_count column with value 1
categorical_df['doctor_count'] = 1

# Display the new categorical DataFrame
categorical_df.head()

   patient_id doctor_name  doctor_count
0     1000025     Dr. Doe             1
1     1002945   Dr. Smith             1
2     1015425     Dr. Lee             1
3     1016277   Dr. Smith             1
4     1017023    Dr. Wong             1

In [13]:
# Step 13: Pivot the DataFrame so each doctor's name becomes a column

doctor_pivot_df = categorical_df.pivot_table(
    index='patient_id',
    columns='doctor_name',
    values='doctor_count',
    aggfunc='sum',
    fill_value=0
)

# Display the pivoted DataFrame
doctor_pivot_df.head()

doctor_name  Dr. Doe  Dr. Lee  Dr. Smith  Dr. Wong
patient_id
61634              0        0          1         0
63375              1        0          0         0
76389              0        1          0         0
95719              0        0          0         1
128059             1        0          0         0

In [14]:
# Step 14: Drop the multi-index from columns using droplevel()

# Check if the pivoted DataFrame has multi-index columns
if isinstance(doctor_pivot_df.columns, pd.MultiIndex):
    doctor_pivot_df.columns = doctor_pivot_df.columns.droplevel(0)
else:
    print("Columns are not MultiIndex, so droplevel() is not required for this output.")

# Reset index so patient_id becomes a normal column again
doctor_onehot_df = doctor_pivot_df.reset_index()

# Display the one-hot encoded doctor DataFrame
doctor_onehot_df.head()

Columns are not MultiIndex, so droplevel() is not required for this output.

doctor_name  patient_id  Dr. Doe  Dr. Lee  Dr. Smith  Dr. Wong
0                 61634        0        0          1         0
1                 63375        1        0          0         0
2                 76389        0        1          0         0
3                 95719        0        0          0         1
4                128059        1        0          0         0

In [15]:
# Step 15: Display the one-hot encoded DataFrame

doctor_onehot_df

doctor_name  patient_id  Dr. Doe  Dr. Lee  Dr. Smith  Dr. Wong
0                 61634        0        0          1         0
1                 63375        1        0          0         0
2                 76389        0        1          0         0
3                 95719        0        0          0         1
4                128059        1        0          0         0
..                  ...      ...      ...        ...       ...
629             1369821        0        1          0         0
630             1371026        0        0          0         1
631             1371920        0        0          0         1
632             8233704        0        0          1         0
633            13454352        1        0          0         0

[634 rows x 5 columns]

In [16]:
# Step 16: Merge the one-hot encoded doctor DataFrame back to the filtered cancer dataset

combined_df = cancer_df_filtered.merge(
    doctor_onehot_df,
    on='patient_id',
    how='left'
)

# Display the final combined DataFrame
combined_df.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe,1,0,0,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith,0,0,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee,0,1,0,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith,0,0,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong,0,0,0,2

In [17]:
# Step 17: Display the final combined DataFrame

combined_df

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,doctor_name,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,Dr. Doe,1,0,0,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,Dr. Smith,0,0,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,Dr. Lee,0,1,0,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,Dr. Smith,0,0,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,Dr. Wong,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671,776715,3.0,1.0,1,1,3,2,1.0,1.0,1,benign,Dr. Lee,0,1,0,0
672,841769,2.0,1.0,1,1,2,1,1.0,1.0,1,benign,Dr. Smith,0,0,1,0
673,888820,5.0,10.0,10,3,7,3,8.0,10.0,2,malignant,Dr. Lee,0,1,0,0
674,897471,4.0,8.0,6,4,3,4,10.0,6.0,1,malignant,Dr. Lee,0,1,0,1
675,897471,4.0,8.0,8,5,4,5,10.0,4.0,1,malignant,Dr. Wong,0,1,0,1

In [18]:
# Step 18: Drop the doctor_name column from the combined DataFrame

combined_df = combined_df.drop(columns=['doctor_name'])

# Display the updated combined DataFrame
combined_df.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,1,0,0,0
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,0,0,1,0
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,0,1,0,0
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,0,0,1,0
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,0,0,0,2

In [19]:
# Step 19: Define a function to classify cell type as normal or abnormal

def celltypelabel(x):
    if ((x['cell_size_uniformity'] > 5) &
        (x['cell_shape_uniformity'] > 5)):
        return 'normal'
    else:
        return 'abnormal'

In [20]:
# Step 20: Use apply() to create a new column named cell_type_label

combined_df['cell_type_label'] = combined_df.apply(celltypelabel, axis=1)

# Display the updated DataFrame
combined_df.head()

,patient_id,clump_thickness,cell_size_uniformity,cell_shape_uniformity,marginal_adhesion,single_ep_cell_size,bare_nuclei,bland_chromatin,normal_nucleoli,mitoses,class,Dr. Doe,Dr. Lee,Dr. Smith,Dr. Wong,cell_type_label
0,1000025,5.0,1.0,1,1,2,1,3.0,1.0,1,benign,1,0,0,0,abnormal
1,1002945,5.0,4.0,4,5,7,10,3.0,2.0,1,benign,0,0,1,0,abnormal
2,1015425,3.0,1.0,1,1,2,2,3.0,1.0,1,benign,0,1,0,0,abnormal
3,1016277,6.0,8.0,8,1,3,4,3.0,7.0,1,benign,0,0,1,0,normal
4,1017023,4.0,1.0,1,3,2,1,3.0,1.0,1,benign,0,0,0,2,abnormal

In [21]:
# Final Step: Save the final combined DataFrame as a CSV file

combined_df.to_csv("lab7_final_combined_dataframe.csv", index=False)

print("Final combined DataFrame saved successfully as lab7_final_combined_dataframe.csv")
print("Final dataset shape:", combined_df.shape)

Final combined DataFrame saved successfully as lab7_final_combined_dataframe.csv
Final dataset shape: (676, 16)